"use server";
import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/lib/supabase-server";
function cid(){return process.env.NURIA_DEV_COMPANY_ID??null} function uid(){return process.env.NURIA_DEV_USER_ID??null} function txt(v:FormDataEntryValue|null){const s=typeof v==="string"?v.trim():"";return s||null} function req(fd:FormData,k:string){const v=txt(fd.get(k));if(!v)throw new Error("Pflichtfeld fehlt.");return v}
async function own(table:string,companyId:string,id:string|null,required=false){if(!id){if(required)throw new Error("Pflichtfeld fehlt.");return null}const s=getSupabaseServerClient();if(!s)return null;const{data}=await s.from(table).select("id").eq("company_id",companyId).eq("id",id).maybeSingle();if(!data)throw new Error("Zuweisung ist ungültig.");return id}
async function audit(companyId:string,type:string,id:string,action:string,row:unknown){const s=getSupabaseServerClient();if(s)await s.from("billing_audit_logs").insert({company_id:companyId,record_type:type,record_id:id,changed_by:uid(),action,new_values:row})}
async function itemPayload(fd:FormData,companyId:string){const q=Number(req(fd,"quantity"));const p=Number(req(fd,"unit_price"));if(q<=0)throw new Error("Menge ist ungültig.");if(p<0)throw new Error("Einzelpreis ist ungültig.");return{client_id:await own("clients",companyId,req(fd,"client_id"),true),employee_id:await own("profiles",companyId,txt(fd.get("employee_id"))),shift_id:await own("shifts",companyId,txt(fd.get("shift_id"))),tour_id:await own("tours",companyId,txt(fd.get("tour_id"))),tour_stop_id:await own("tour_stops",companyId,txt(fd.get("tour_stop_id"))),time_entry_id:await own("time_entries",companyId,txt(fd.get("time_entry_id"))),service_date:req(fd,"service_date"),service_type:req(fd,"service_type"),description:req(fd,"description"),quantity:q,unit:req(fd,"unit"),unit_price:p,total_amount:q*p,payer_type:req(fd,"payer_type"),payer_name:txt(fd.get("payer_name")),status:req(fd,"status"),notes:txt(fd.get("notes"))}}
export async function createBillingItem(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();if(!s||!companyId)return;const row={...(await itemPayload(fd,companyId)),company_id:companyId,created_by:uid(),updated_by:uid()};const{data}=await s.from("billing_items").insert(row).select("id").single();if(data)await audit(companyId,"billing_item",data.id,"created",row);revalidatePath("/dashboard/abrechnung")}
export async function updateBillingItem(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"id");if(!s||!companyId)return;const row={...(await itemPayload(fd,companyId)),updated_by:uid()};await s.from("billing_items").update(row).eq("id",id).eq("company_id",companyId);await audit(companyId,"billing_item",id,"updated",row);revalidatePath("/dashboard/abrechnung")}
export async function changeBillingItemStatus(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"id");const status=req(fd,"status");if(!s||!companyId)return;await s.from("billing_items").update({status,updated_by:uid()}).eq("id",id).eq("company_id",companyId);await audit(companyId,"billing_item",id,status,{status});revalidatePath("/dashboard/abrechnung")}
export async function createInvoice(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();if(!s||!companyId)return;const clientId=await own("clients",companyId,req(fd,"client_id"),true);const start=req(fd,"billing_period_start");const end=req(fd,"billing_period_end");const{data:items}=await s.from("billing_items").select("*").eq("company_id",companyId).eq("client_id",clientId).eq("status","ready").gte("service_date",start).lte("service_date",end);const rows=items??[];const subtotal=rows.reduce((a,i)=>a+Number(i.total_amount??0),0);const invoice={company_id:companyId,client_id:clientId,invoice_number:`RE-${Date.now()}`,invoice_date:new Date().toISOString().slice(0,10),billing_period_start:start,billing_period_end:end,due_date:txt(fd.get("due_date")),recipient_name:req(fd,"recipient_name"),recipient_email:txt(fd.get("recipient_email")),recipient_address:txt(fd.get("recipient_address")),subtotal_amount:subtotal,tax_amount:0,total_amount:subtotal,status:"draft",payment_status:"open",notes:txt(fd.get("notes")),created_by:uid(),updated_by:uid()};const{data}=await s.from("invoices").insert(invoice).select("id").single();if(data&&rows.length){await s.from("invoice_items").insert(rows.map(i=>({company_id:companyId,invoice_id:data.id,billing_item_id:i.id,description:i.description,quantity:i.quantity,unit:i.unit,unit_price:i.unit_price,total_amount:i.total_amount})));await s.from("billing_items").update({status:"billed",updated_by:uid()}).eq("company_id",companyId).in("id",rows.map(i=>i.id));await audit(companyId,"invoice",data.id,"created",invoice)}revalidatePath("/dashboard/abrechnung")}
export async function updateInvoiceStatus(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"id");const field=req(fd,"field");const value=req(fd,"value");if(!s||!companyId)return;await s.from("invoices").update({[field]:value,updated_by:uid()}).eq("id",id).eq("company_id",companyId);await audit(companyId,"invoice",id,value,{[field]:value});revalidatePath("/dashboard/abrechnung")}
