"use server";
import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/lib/supabase-server";
import type { CareCategory, CareStatus, CareVisibility } from "@/lib/care-documentation";
const cats=["pflegebericht","uebergabe","beobachtung","massnahme","vitalwerte","wunde","medikation","ereignis","sonstiges"] as const; const statuses=["draft","submitted","reviewed","archived"] as const; const vis=["internal","care_team","management"] as const;
function cid(){return process.env.NURIA_DEV_COMPANY_ID??null} function uid(){return process.env.NURIA_DEV_USER_ID??null} function txt(v:FormDataEntryValue|null){const s=typeof v==="string"?v.trim():""; return s||null} function req(fd:FormData,k:string){const v=txt(fd.get(k)); if(!v) throw new Error("Pflichtfeld fehlt."); return v}
function cat(v:string|null):CareCategory{if(!v||!cats.includes(v as CareCategory)) throw new Error("Kategorie ist ungültig."); return v as CareCategory} function stat(v:string|null):CareStatus{if(!v||!statuses.includes(v as CareStatus)) throw new Error("Status ist ungültig."); return v as CareStatus} function visibility(v:string|null):CareVisibility{if(!v||!vis.includes(v as CareVisibility)) throw new Error("Sichtbarkeit ist ungültig."); return v as CareVisibility}
async function own(table:string,companyId:string,id:string|null,required=false){if(!id){if(required) throw new Error("Pflichtfeld fehlt."); return null} const s=getSupabaseServerClient(); if(!s) return null; const {data}=await s.from(table).select("id").eq("company_id",companyId).eq("id",id).maybeSingle(); if(!data) throw new Error("Zuweisung ist ungültig."); return id}
async function payload(fd:FormData,companyId:string){return{client_id:await own("clients",companyId,req(fd,"client_id"),true),employee_id:await own("profiles",companyId,txt(fd.get("employee_id"))),shift_id:await own("shifts",companyId,txt(fd.get("shift_id"))),tour_id:await own("tours",companyId,txt(fd.get("tour_id"))),tour_stop_id:await own("tour_stops",companyId,txt(fd.get("tour_stop_id"))),documentation_date:req(fd,"documentation_date"),documentation_time:txt(fd.get("documentation_time")),category:cat(txt(fd.get("category"))),title:req(fd,"title"),content:req(fd,"content"),status:stat(txt(fd.get("status"))),visibility:visibility(txt(fd.get("visibility")))}}
async function audit(companyId:string,id:string,action:string,row:unknown){const s=getSupabaseServerClient(); if(s) await s.from("care_documentation_audit_logs").insert({company_id:companyId,documentation_id:id,changed_by:uid(),action,new_values:row})}
async function vitals(fd:FormData,companyId:string,docId:string,clientId:string){const keys=["blood_pressure_systolic","blood_pressure_diastolic","pulse","temperature","blood_sugar","weight","oxygen_saturation","vital_notes"]; if(!keys.some(k=>txt(fd.get(k)))) return; const s=getSupabaseServerClient(); if(!s) return; await s.from("care_vitals").upsert({company_id:companyId,documentation_id:docId,client_id:clientId,measured_at:new Date().toISOString(),blood_pressure_systolic:txt(fd.get("blood_pressure_systolic")),blood_pressure_diastolic:txt(fd.get("blood_pressure_diastolic")),pulse:txt(fd.get("pulse")),temperature:txt(fd.get("temperature")),blood_sugar:txt(fd.get("blood_sugar")),weight:txt(fd.get("weight")),oxygen_saturation:txt(fd.get("oxygen_saturation")),notes:txt(fd.get("vital_notes")),created_by:uid()},{onConflict:"documentation_id"})}
export async function createCareDoc(fd:FormData){const s=getSupabaseServerClient(); const companyId=cid(); if(!s||!companyId)return; const row={...(await payload(fd,companyId)),company_id:companyId,created_by:uid(),updated_by:uid()}; const {data}=await s.from("care_documentation").insert(row).select("id, client_id").single(); if(data){await vitals(fd,companyId,data.id,data.client_id); await audit(companyId,data.id,"created",row)} revalidatePath("/dashboard/pflegedokumentation")}
export async function updateCareDoc(fd:FormData){const s=getSupabaseServerClient(); const companyId=cid(); const id=req(fd,"id"); if(!s||!companyId)return; const row={...(await payload(fd,companyId)),updated_by:uid()}; await s.from("care_documentation").update(row).eq("id",id).eq("company_id",companyId); if(row.client_id) await vitals(fd,companyId,id,row.client_id); await audit(companyId,id,"updated",row); revalidatePath("/dashboard/pflegedokumentation")}
export async function reviewCareDoc(fd:FormData){const s=getSupabaseServerClient(); const companyId=cid(); const id=req(fd,"id"); const next=stat(req(fd,"status")); if(!s||!companyId)return; const row=next==="reviewed"?{status:next,reviewed_by:uid(),reviewed_at:new Date().toISOString(),updated_by:uid()}:{status:next,updated_by:uid()}; await s.from("care_documentation").update(row).eq("id",id).eq("company_id",companyId); await audit(companyId,id,next==="reviewed"?"reviewed":"archived",row); revalidatePath("/dashboard/pflegedokumentation")}
