"use server";
import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/lib/supabase-server";
function cid(){return process.env.NURIA_DEV_COMPANY_ID??null} function uid(){return process.env.NURIA_DEV_USER_ID??null} function txt(v:FormDataEntryValue|null){const s=typeof v==="string"?v.trim():"";return s||null} function req(fd:FormData,k:string){const v=txt(fd.get(k));if(!v)throw new Error("Pflichtfeld fehlt.");return v}
async function ownUser(companyId:string,id:string){const s=getSupabaseServerClient();if(!s)return null;const{data}=await s.from("profiles").select("id,role").eq("company_id",companyId).eq("id",id).maybeSingle();if(!data)throw new Error("Teilnehmer ist ungültig.");return data}
async function audit(companyId:string,id:string,action:string,row:unknown){const s=getSupabaseServerClient();if(s)await s.from("conversation_audit_logs").insert({company_id:companyId,conversation_id:id,changed_by:uid(),action,new_values:row})}
export async function createDirectConversation(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const userId=uid();const recipient=req(fd,"recipient_id");const body=req(fd,"body");if(!s||!companyId||!userId)return;await ownUser(companyId,recipient);const{data:conv}=await s.from("conversations").insert({company_id:companyId,title:"Einzelchat",conversation_type:"direct",status:"active",created_by:userId,last_message_at:new Date().toISOString()}).select("id").single();if(!conv)return;await s.from("conversation_participants").insert([{company_id:companyId,conversation_id:conv.id,user_id:userId,role:"owner",last_read_at:new Date().toISOString()},{company_id:companyId,conversation_id:conv.id,user_id:recipient,role:"participant"}]);await s.from("messages").insert({company_id:companyId,conversation_id:conv.id,sender_id:userId,body,message_type:"text"});await audit(companyId,conv.id,"created",{recipient});revalidatePath("/dashboard/kommunikation")}
export async function createGroupConversation(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const userId=uid();const title=req(fd,"title");const body=txt(fd.get("body"));const ids=fd.getAll("participant_ids").map(v=>String(v)).filter(Boolean);if(!s||!companyId||!userId||ids.length===0)return;for(const id of ids)await ownUser(companyId,id);const{data:conv}=await s.from("conversations").insert({company_id:companyId,title,conversation_type:"group",status:"active",created_by:userId,last_message_at:body?new Date().toISOString():null}).select("id").single();if(!conv)return;await s.from("conversation_participants").insert([{company_id:companyId,conversation_id:conv.id,user_id:userId,role:"owner",last_read_at:new Date().toISOString()},...ids.map(id=>({company_id:companyId,conversation_id:conv.id,user_id:id,role:"participant"}))]);if(body)await s.from("messages").insert({company_id:companyId,conversation_id:conv.id,sender_id:userId,body,message_type:"text"});await audit(companyId,conv.id,"created",{title,ids});revalidatePath("/dashboard/kommunikation")}
export async function sendMessage(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const userId=uid();const conversationId=req(fd,"conversation_id");const body=req(fd,"body");if(!s||!companyId||!userId)return;const{data:conv}=await s.from("conversations").select("id").eq("company_id",companyId).eq("id",conversationId).maybeSingle();if(!conv)return;const now=new Date().toISOString();await s.from("messages").insert({company_id:companyId,conversation_id:conversationId,sender_id:userId,body,message_type:"text"});await s.from("conversations").update({last_message_at:now}).eq("id",conversationId).eq("company_id",companyId);await s.from("conversation_participants").upsert({company_id:companyId,conversation_id:conversationId,user_id:userId,last_read_at:now},{onConflict:"conversation_id,user_id"});await audit(companyId,conversationId,"message_sent",{body});revalidatePath("/dashboard/kommunikation")}
export async function markConversationRead(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const userId=uid();const conversationId=req(fd,"conversation_id");if(!s||!companyId||!userId)return;await s.from("conversation_participants").upsert({company_id:companyId,conversation_id:conversationId,user_id:userId,last_read_at:new Date().toISOString()},{onConflict:"conversation_id,user_id"});revalidatePath("/dashboard/kommunikation")}
export async function archiveConversation(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"conversation_id");if(!s||!companyId)return;await s.from("conversations").update({status:"archived",archived_at:new Date().toISOString()}).eq("id",id).eq("company_id",companyId);await audit(companyId,id,"archived",{});revalidatePath("/dashboard/kommunikation")}
export async function addParticipant(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const conversationId=req(fd,"conversation_id");const userId=req(fd,"user_id");if(!s||!companyId)return;const u=await ownUser(companyId,userId);if(!u)return;await s.from("conversation_participants").upsert({company_id:companyId,conversation_id:conversationId,user_id:userId,role:"participant"},{onConflict:"conversation_id,user_id"});await audit(companyId,conversationId,"participants_updated",{userId});revalidatePath("/dashboard/kommunikation")}
export async function removeParticipant(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const conversationId=req(fd,"conversation_id");const userId=req(fd,"user_id");if(!s||!companyId||userId===uid())return;await s.from("conversation_participants").delete().eq("company_id",companyId).eq("conversation_id",conversationId).eq("user_id",userId);await audit(companyId,conversationId,"participants_updated",{userId});revalidatePath("/dashboard/kommunikation")}
