import { getSupabaseServerClient } from "@/lib/supabase-server";
import type { ActivityLog } from "@/lib/activity-logs";
export type ComplianceCategory="datenschutz"|"zugriffskontrolle"|"rollen_rechte"|"exporte"|"loeschungen"|"dokumentation"|"aufbewahrung"|"technische_massnahmen"|"organisatorische_massnahmen"|"mitarbeiterzugriff"|"pruefprotokolle"|"sonstiges";
export type ComplianceStatus="open"|"in_progress"|"waiting"|"completed"|"overdue"|"archived";export type CompliancePriority="low"|"normal"|"high"|"urgent";export type ComplianceEvidenceType="document"|"note"|"check"|"export_log"|"access_log"|"deletion_log"|"other";
export type Opt={id:string;name:string};export type ComplianceItem={id:string;company_id:string;location_id:string|null;title:string;description:string|null;category:ComplianceCategory;status:ComplianceStatus;priority:CompliancePriority;responsible_user_id:string|null;due_date:string|null;completed_at:string|null;last_checked_at:string|null;notes:string|null;created_at:string;updated_at:string;archived_at:string|null;location_name:string|null;responsible_name:string|null;evidence_count:number};
export type ComplianceEvidence={id:string;company_id:string;compliance_item_id:string;document_id:string|null;title:string;description:string|null;evidence_type:ComplianceEvidenceType;created_at:string;updated_at:string;item_title:string|null;document_title:string|null;created_by_name:string|null};
export type ComplianceData={items:ComplianceItem[];evidence:ComplianceEvidence[];logs:ActivityLog[];locations:Opt[];employees:Opt[];documents:Opt[];stats:{total:number;open:number;overdue:number;evidence:number;accessToday:number;exportsMonth:number;deletions:number;warningsErrors:number};exportPrepared:boolean};
function cid(){return process.env.NURIA_DEV_COMPANY_ID??null}function name(r:{first_name?:string|null;last_name?:string|null;email?:string|null}){return[first_nameSafe(r.first_name),first_nameSafe(r.last_name)].filter(Boolean).join(" ")||r.email||"Nicht hinterlegt"}function first_nameSafe(v?:string|null){return v??""}
export async function getComplianceData():Promise<ComplianceData>{const s=getSupabaseServerClient();const c=cid();const empty={items:[],evidence:[],logs:[],locations:[],employees:[],documents:[],stats:{total:0,open:0,overdue:0,evidence:0,accessToday:0,exportsMonth:0,deletions:0,warningsErrors:0},exportPrepared:true};if(!s||!c)return empty;const[{data:items},{data:evidence},{data:logs},{data:locations},{data:employees},{data:documents}]=await Promise.all([
s.from("compliance_items").select("id,company_id,location_id,title,description,category,status,priority,responsible_user_id,due_date,completed_at,last_checked_at,notes,created_at,updated_at,archived_at,company_locations(name),profiles(first_name,last_name,email)").eq("company_id",c).order("updated_at",{ascending:false}),
s.from("compliance_evidence").select("id,company_id,compliance_item_id,document_id,title,description,evidence_type,created_at,updated_at,compliance_items(title),documents(file_name),profiles(first_name,last_name,email)").eq("company_id",c).order("created_at",{ascending:false}),
s.from("activity_logs").select("*").eq("company_id",c).order("created_at",{ascending:false}).limit(300),
s.from("company_locations").select("id,name").eq("company_id",c).order("name"),
s.from("profiles").select("id,first_name,last_name,email").eq("company_id",c).order("last_name"),
s.from("documents").select("id,file_name").eq("company_id",c).order("created_at",{ascending:false})]);const ev=(evidence??[]) as any[];const normItems=((items??[]) as any[]).map(i=>({...i,category:i.category??"sonstiges",status:i.status??"open",priority:i.priority??"normal",location_name:Array.isArray(i.company_locations)?i.company_locations[0]?.name??null:i.company_locations?.name??null,responsible_name:Array.isArray(i.profiles)?name(i.profiles[0]??{}):name(i.profiles??{}),evidence_count:ev.filter(e=>e.compliance_item_id===i.id).length})) as ComplianceItem[];const normEv=ev.map(e=>({...e,evidence_type:e.evidence_type??"note",item_title:Array.isArray(e.compliance_items)?e.compliance_items[0]?.title??null:e.compliance_items?.title??null,document_title:Array.isArray(e.documents)?e.documents[0]?.file_name??null:e.documents?.file_name??null,created_by_name:Array.isArray(e.profiles)?name(e.profiles[0]??{}):name(e.profiles??{})})) as ComplianceEvidence[];const normLogs=(logs??[]) as ActivityLog[];const today=new Date();today.setHours(0,0,0,0);const month=new Date();month.setDate(1);month.setHours(0,0,0,0);return{items:normItems,evidence:normEv,logs:normLogs,locations:(locations??[]) as Opt[],employees:((employees??[]) as any[]).map(e=>({id:e.id,name:name(e)})),documents:((documents??[]) as any[]).map(d=>({id:d.id,name:d.file_name??"Dokument"})),stats:{total:normItems.filter(i=>i.status!=="archived").length,open:normItems.filter(i=>i.status==="open").length,overdue:normItems.filter(i=>i.status!=="completed"&&i.status!=="archived"&&i.due_date&&new Date(i.due_date)<today).length,evidence:normEv.length,accessToday:normLogs.filter(l=>["viewed","login","logout","failed_login"].includes(l.action)&&new Date(l.created_at)>=today).length,exportsMonth:normLogs.filter(l=>(l.entity_type==="export_job"||l.action==="exported")&&new Date(l.created_at)>=month).length,deletions:normLogs.filter(l=>["deleted","archived"].includes(l.action)).length,warningsErrors:normLogs.filter(l=>l.severity==="warning"||l.severity==="error"||l.severity==="critical"||l.status==="failed").length},exportPrepared:true}}
