"use server";
import { randomUUID } from "crypto";
import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/lib/supabase-server";
const bucket="company-documents"; const allowed=["application/pdf","image/jpeg","image/png","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]; const max=20*1024*1024;
function cid(){return process.env.NURIA_DEV_COMPANY_ID??null} function uid(){return process.env.NURIA_DEV_USER_ID??null} function txt(v:FormDataEntryValue|null){const s=typeof v==="string"?v.trim():"";return s||null} function req(fd:FormData,k:string){const v=txt(fd.get(k));if(!v)throw new Error("Pflichtfeld fehlt.");return v}
async function own(table:string,companyId:string,id:string|null){if(!id)return null;const s=getSupabaseServerClient();if(!s)return null;const{data}=await s.from(table).select("id").eq("company_id",companyId).eq("id",id).maybeSingle();if(!data)throw new Error("Zuweisung ist ungültig.");return id}
async function audit(companyId:string,id:string,action:string,row:unknown){const s=getSupabaseServerClient();if(s)await s.from("document_audit_logs").insert({company_id:companyId,document_id:id,changed_by:uid(),action,new_values:row})}
async function meta(fd:FormData,companyId:string){return{title:req(fd,"title"),description:txt(fd.get("description")),category:req(fd,"category"),visibility:req(fd,"visibility"),status:req(fd,"status"),client_id:await own("clients",companyId,txt(fd.get("client_id"))),employee_id:await own("profiles",companyId,txt(fd.get("employee_id"))),shift_id:await own("shifts",companyId,txt(fd.get("shift_id"))),tour_id:await own("tours",companyId,txt(fd.get("tour_id"))),tour_stop_id:await own("tour_stops",companyId,txt(fd.get("tour_stop_id"))),invoice_id:await own("invoices",companyId,txt(fd.get("invoice_id"))),billing_item_id:await own("billing_items",companyId,txt(fd.get("billing_item_id")))}}
export async function uploadDocument(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();if(!s||!companyId)return;const file=fd.get("file");if(!(file instanceof File)||file.size===0)throw new Error("Datei fehlt.");if(file.size>max)throw new Error("Datei ist zu groß.");if(!allowed.includes(file.type))throw new Error("Dateityp ist nicht erlaubt.");const id=randomUUID();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${companyId}/${id}/${safe}`;const up=await s.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const row={...(await meta(fd,companyId)),id,company_id:companyId,uploaded_by:uid(),file_name:file.name,file_path:path,file_type:safe.split(".").pop()?.toLowerCase()??null,mime_type:file.type,file_size:file.size,storage_bucket:bucket,uploaded_at:new Date().toISOString()};await s.from("documents").insert(row);await audit(companyId,id,"uploaded",row);revalidatePath("/dashboard/dokumente")}
export async function updateDocument(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"id");if(!s||!companyId)return;const row=await meta(fd,companyId);await s.from("documents").update(row).eq("id",id).eq("company_id",companyId);await audit(companyId,id,"updated",row);revalidatePath("/dashboard/dokumente")}
export async function archiveDocument(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"id");if(!s||!companyId)return;await s.from("documents").update({status:"archived"}).eq("id",id).eq("company_id",companyId);await audit(companyId,id,"archived",{status:"archived"});revalidatePath("/dashboard/dokumente")}
export async function deleteDocument(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"id");if(!s||!companyId)return;await s.from("documents").update({status:"deleted",deleted_at:new Date().toISOString()}).eq("id",id).eq("company_id",companyId);await audit(companyId,id,"deleted",{status:"deleted"});revalidatePath("/dashboard/dokumente")}
export async function getDocumentSignedUrl(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"id");if(!s||!companyId)return null;const{data}=await s.from("documents").select("file_path, storage_bucket, mime_type").eq("id",id).eq("company_id",companyId).maybeSingle();if(!data?.file_path)return null;const signed=await s.storage.from(data.storage_bucket??bucket).createSignedUrl(data.file_path,300);if(signed.error)return null;await audit(companyId,id,"downloaded",{id});return {url:signed.data.signedUrl,mimeType:data.mime_type};}
