"use server";
import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/lib/supabase-server";
import type { ExportFormat, ExportType } from "@/lib/exports";
import { writeActivityLog } from "@/lib/activity-log-actions";
const types=["clients","employees","locations","shifts","tours","time_entries","care_documentation","documents_metadata","billing","applicants","website_online","qm_md","activity_logs"] as const; const formats=["csv","json"] as const;
const tableMap:Record<ExportType,string[]>={clients:["clients"],employees:["profiles"],locations:["company_locations"],shifts:["shifts"],tours:["tours","tour_stops"],time_entries:["time_entries"],care_documentation:["care_documentation"],documents_metadata:["documents"],billing:["billing_items","invoices","invoice_items"],applicants:["applicants"],website_online:["website_leads","online_presence_tasks"],qm_md:["qm_items","qm_measures","qm_evidence"],activity_logs:["care_documentation_audit_logs"]};
function cid(){return process.env.NURIA_DEV_COMPANY_ID??null} function uid(){return process.env.NURIA_DEV_USER_ID??null} function text(v:FormDataEntryValue|null){const s=typeof v==="string"?v.trim():"";return s||null} function req(fd:FormData,k:string){const v=text(fd.get(k));if(!v)throw new Error("Pflichtfeld fehlt.");return v} function safeName(v:string){return v.toLowerCase().replace(/[^a-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")}
function csv(rows:Record<string, unknown>[]){if(rows.length===0)return "";const keys=Array.from(rows.reduce((s,r)=>{Object.keys(r??{}).forEach(k=>s.add(k));return s},new Set<string>()));return [keys.join(","),...rows.map(r=>keys.map(k=>JSON.stringify(r[k]??"")).join(","))].join("\n")}
async function load(s:any,companyId:string,type:ExportType,from:string|null,to:string|null){const out:Record<string,unknown[]>={};for(const table of tableMap[type]){let q=s.from(table).select("*").eq("company_id",companyId);if(from)q=q.gte("created_at",from);if(to)q=q.lte("created_at",to);const {data,error}=await q;if(error)throw new Error(error.message);out[table]=data??[]}return out}
export async function createExportJob(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();if(!s||!companyId)return;const export_type=req(fd,"export_type") as ExportType;const format=req(fd,"format") as ExportFormat;if(!types.includes(export_type))throw new Error("Exportbereich ist ungültig.");if(!formats.includes(format as "csv"|"json"))throw new Error("PDF-Export wird vorbereitet.");const date_from=text(fd.get("date_from"));const date_to=text(fd.get("date_to"));if(date_from&&date_to&&new Date(date_from)>new Date(date_to))throw new Error("Zeitraum ist ungültig.");const requestedName=text(fd.get("file_name"));const actor=uid();const {data:job,error}=await s.from("export_jobs").insert({company_id:companyId,requested_by:actor,export_type,format,status:"processing",date_from,date_to,filters:{}}).select("id").single();if(error||!job)throw new Error(error?.message??"Export konnte nicht erstellt werden.");await writeActivityLog({companyId,userId:actor,action:"created",entityType:"export_job",entityId:job.id,entityLabel:export_type,message:"Exportauftrag wurde erstellt.",status:"pending"});try{const rows=await load(s,companyId,export_type,date_from,date_to);const body=format==="json"?JSON.stringify(rows,null,2):Object.entries(rows).map(([table,data])=>`# ${table}\n${csv(data as any[])}`).join("\n\n");const fileName=safeName(requestedName||`${export_type}-${new Date().toISOString().slice(0,10)}.${format}`);const path=`${companyId}/${job.id}/${fileName}`;const {error:uploadError}=await s.storage.from("company-exports").upload(path,body,{contentType:format==="json"?"application/json":"text/csv",upsert:true});if(uploadError)throw new Error(uploadError.message);await s.from("export_jobs").update({status:"completed",file_name:fileName,file_path:path,file_size:new TextEncoder().encode(body).length,storage_bucket:"company-exports",completed_at:new Date().toISOString()}).eq("id",job.id).eq("company_id",companyId);await writeActivityLog({companyId,userId:actor,action:"exported",entityType:"export_job",entityId:job.id,entityLabel:fileName,message:"Exportdatei wurde erstellt.",metadata:{export_type,format}})}catch(e){const message=e instanceof Error?e.message:"Export fehlgeschlagen";await s.from("export_jobs").update({status:"failed",error_message:message}).eq("id",job.id).eq("company_id",companyId);await writeActivityLog({companyId,userId:actor,action:"error",entityType:"export_job",entityId:job.id,entityLabel:export_type,severity:"error",status:"failed",message})}revalidatePath("/dashboard/exporte");revalidatePath("/dashboard/aktivitaeten")}
export async function deleteExportJob(fd:FormData){const s=getSupabaseServerClient();const companyId=cid();const id=req(fd,"id");if(!s||!companyId)return;await s.from("export_jobs").update({status:"deleted",deleted_at:new Date().toISOString()}).eq("id",id).eq("company_id",companyId);await writeActivityLog({companyId,userId:uid(),action:"deleted",entityType:"export_job",entityId:id,message:"Exportauftrag wurde in den Papierkorb verschoben."});revalidatePath("/dashboard/exporte");revalidatePath("/dashboard/aktivitaeten")}
