import { getSupabaseServerClient } from "@/lib/supabase-server";
import { getCurrentUserContext } from "@/lib/current-user";

export type ExportType = "clients"|"employees"|"locations"|"shifts"|"tours"|"time_entries"|"care_documentation"|"documents_metadata"|"billing"|"applicants"|"website_online"|"qm_md"|"activity_logs";
export type ExportFormat = "csv"|"json"|"pdf";
export type ExportStatus = "pending"|"processing"|"completed"|"failed"|"deleted";
export type ExportJob={id:string;company_id:string;requested_by:string|null;export_type:ExportType;format:ExportFormat;status:ExportStatus;date_from:string|null;date_to:string|null;filters:Record<string,unknown>;file_name:string|null;file_path:string|null;file_size:number|null;storage_bucket:string|null;error_message:string|null;created_at:string;updated_at:string;completed_at:string|null;deleted_at:string|null;requested_by_name:string|null;signed_url:string|null};
export type ExportsData={jobs:ExportJob[];requesters:{id:string;name:string}[];stats:{total:number;completed:number;running:number;failed:number;csv:number;json:number;pdf:number;storage:number};exportPrepared:boolean};
function name(r:{first_name?:string|null;last_name?:string|null;email?:string|null}){return [r.first_name,r.last_name].filter(Boolean).join(" ")||r.email||"Nicht hinterlegt"}
export async function getExportsData():Promise<ExportsData>{const s=getSupabaseServerClient();const context=await getCurrentUserContext();const c=context?.companyId??null;const empty={jobs:[],requesters:[],stats:{total:0,completed:0,running:0,failed:0,csv:0,json:0,pdf:0,storage:0},exportPrepared:false};if(!s||!c)return empty;const[{data:jobs},{data:profiles}]=await Promise.all([s.from("export_jobs").select("id,company_id,requested_by,export_type,format,status,date_from,date_to,filters,file_name,file_path,file_size,storage_bucket,error_message,created_at,updated_at,completed_at,deleted_at,profiles(first_name,last_name,email)").eq("company_id",c).order("created_at",{ascending:false}),s.from("profiles").select("id,first_name,last_name,email").eq("company_id",c).order("last_name")]);const normalized=await Promise.all(((jobs??[]) as any[]).map(async j=>{let signed_url:null|string=null;if(j.status==="completed"&&j.file_path&&j.storage_bucket){const {data}=await s.storage.from(j.storage_bucket).createSignedUrl(j.file_path,3600);signed_url=data?.signedUrl??null}return{...j,requested_by_name:Array.isArray(j.profiles)?name(j.profiles[0]??{}):name(j.profiles??{}),signed_url} as ExportJob}));return{jobs:normalized,requesters:((profiles??[]) as any[]).map(p=>({id:p.id,name:name(p)})),stats:{total:normalized.filter(j=>j.status!=="deleted").length,completed:normalized.filter(j=>j.status==="completed").length,running:normalized.filter(j=>j.status==="pending"||j.status==="processing").length,failed:normalized.filter(j=>j.status==="failed").length,csv:normalized.filter(j=>j.format==="csv").length,json:normalized.filter(j=>j.format==="json").length,pdf:normalized.filter(j=>j.format==="pdf").length,storage:normalized.reduce((sum,j)=>sum+(j.file_size??0),0)},exportPrepared:true}}
