"use server";
import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/lib/supabase-server";
import { writeActivityLog } from "@/lib/activity-log-actions";
import { calculatePlan, plans, type BillingInterval } from "@/lib/payment";

function companyId(){return process.env.NURIA_DEV_COMPANY_ID??null} function userId(){return process.env.NURIA_DEV_USER_ID??null} function text(fd:FormData,k:string){const v=fd.get(k);return typeof v==="string"&&v.trim()?v.trim():null}
function email(v:string|null){if(!v)return null;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw new Error("E-Mail ist ungültig.");return v}

export async function markPaymentSent(){const s=getSupabaseServerClient();const c=companyId();const u=userId();if(!s||!c)return;const {data:company}=await s.from("companies").select("payment_status,billing_interval,package_id").eq("id",c).maybeSingle();if(!company)return;if(company.payment_status==="payment_marked_as_sent"||company.payment_status==="active")return;const {data:sub}=await s.from("company_subscriptions").select("*").eq("company_id",c).neq("status","cancelled").order("created_at",{ascending:false}).limit(1).maybeSingle();const interval=(sub?.billing_interval??company.billing_interval??"monthly") as BillingInterval;const plan=calculatePlan(interval in plans?interval:"monthly");const subscriptionId=sub?.id??null;const now=new Date().toISOString();await s.from("companies").update({payment_status:"payment_marked_as_sent",payment_marked_at:now,payment_due_check_at:new Date(Date.now()+5*24*60*60*1000).toISOString(),package_id:sub?.package_id??company.package_id??plan.packageId,billing_interval:interval}).eq("id",c);if(subscriptionId){await s.from("company_subscriptions").update({status:"payment_marked_as_sent"}).eq("id",subscriptionId).eq("company_id",c)}await s.from("company_payment_logs").insert({company_id:c,subscription_id:subscriptionId,amount:Number(sub?.total_amount??plan.total),currency:"EUR",billing_interval:interval,payment_method:"bank_transfer",status:"marked_as_sent",marked_by:u,marked_at:now,notes:"Überweisung als ausgeführt markiert. Die Zahlung wird intern geprüft."});await writeActivityLog({companyId:c,userId:u,action:"updated",entityType:"company_settings",entityLabel:"Zahlung & Tarif",message:"Überweisung wurde als ausgeführt markiert."});revalidatePath("/dashboard/zahlung-tarif")}

export async function saveBillingData(formData:FormData){const s=getSupabaseServerClient();const c=companyId();if(!s||!c)return;const billing_email=email(text(formData,"billing_email"));const update={billing_email,name:text(formData,"name"),legal_name:text(formData,"legal_name"),street:text(formData,"street"),house_number:text(formData,"house_number"),postal_code:text(formData,"postal_code"),city:text(formData,"city"),country:text(formData,"country")};await s.from("companies").update(update).eq("id",c);await writeActivityLog({companyId:c,userId:userId(),action:"updated",entityType:"company_settings",entityLabel:"Rechnungsdaten",message:"Rechnungsdaten wurden geändert."});revalidatePath("/dashboard/zahlung-tarif")}
