import { getSupabaseServerClient } from "@/lib/supabase-server";

export type QmCategory = "organisation"|"pflegeprozess"|"dokumentation"|"mitarbeiter"|"hygiene"|"medikamente"|"notfallmanagement"|"datenschutz"|"abrechnung"|"fortbildungen"|"beschwerden"|"md_vorbereitung"|"sonstiges";
export type QmStatus = "open"|"in_progress"|"waiting"|"completed"|"overdue"|"archived";
export type QmMeasureStatus = "open"|"in_progress"|"completed"|"cancelled";
export type QmPriority = "low"|"normal"|"high"|"urgent";
export type EvidenceType = "document"|"note"|"check"|"photo"|"other";
export type QmOption={id:string;name:string};
export type QmItem={id:string;company_id:string;location_id:string|null;title:string;description:string|null;category:QmCategory;status:QmStatus;priority:QmPriority;responsible_user_id:string|null;due_date:string|null;completed_at:string|null;last_checked_at:string|null;notes:string|null;created_at:string;updated_at:string;archived_at:string|null;location_name:string|null;responsible_name:string|null;measure_count:number;evidence_count:number};
export type QmMeasure={id:string;company_id:string;qm_item_id:string;title:string;description:string|null;status:QmMeasureStatus;priority:QmPriority;responsible_user_id:string|null;due_date:string|null;completed_at:string|null;notes:string|null;created_at:string;updated_at:string;item_title:string|null;responsible_name:string|null};
export type QmEvidence={id:string;company_id:string;qm_item_id:string;document_id:string|null;title:string;description:string|null;evidence_type:EvidenceType;created_at:string;updated_at:string;item_title:string|null;document_title:string|null;created_by_name:string|null};
export type QmMdData={items:QmItem[];measures:QmMeasure[];evidence:QmEvidence[];locations:QmOption[];employees:QmOption[];documents:QmOption[];stats:{total:number;open:number;inProgress:number;overdue:number;completed:number;openMeasures:number;evidence:number;archived:number};exportPrepared:boolean};
function cid(){return process.env.NURIA_DEV_COMPANY_ID??null} function name(r:{first_name?:string|null;last_name?:string|null;email?:string|null}){return [r.first_name,r.last_name].filter(Boolean).join(" ")||r.email||"Nicht hinterlegt"}
export async function getQmMdData():Promise<QmMdData>{const supabase=getSupabaseServerClient();const companyId=cid();const empty={items:[],measures:[],evidence:[],locations:[],employees:[],documents:[],stats:{total:0,open:0,inProgress:0,overdue:0,completed:0,openMeasures:0,evidence:0,archived:0},exportPrepared:false};if(!supabase||!companyId)return empty;const[{data:items},{data:measures},{data:evidence},{data:locations},{data:employees},{data:documents}]=await Promise.all([
supabase.from("qm_items").select("id,company_id,location_id,title,description,category,status,priority,responsible_user_id,due_date,completed_at,last_checked_at,notes,created_at,updated_at,archived_at,company_locations(name),profiles(first_name,last_name,email)").eq("company_id",companyId).order("updated_at",{ascending:false}),
supabase.from("qm_measures").select("id,company_id,qm_item_id,title,description,status,priority,responsible_user_id,due_date,completed_at,notes,created_at,updated_at,qm_items(title),profiles(first_name,last_name,email)").eq("company_id",companyId).order("updated_at",{ascending:false}),
supabase.from("qm_evidence").select("id,company_id,qm_item_id,document_id,title,description,evidence_type,created_at,updated_at,qm_items(title),documents(file_name),profiles(first_name,last_name,email)").eq("company_id",companyId).order("created_at",{ascending:false}),
supabase.from("company_locations").select("id,name").eq("company_id",companyId).order("name"),
supabase.from("profiles").select("id,first_name,last_name,email").eq("company_id",companyId).order("last_name"),
supabase.from("documents").select("id,file_name").eq("company_id",companyId).order("created_at",{ascending:false})]);
const ms=(measures??[]) as any[];const ev=(evidence??[]) as any[];const normItems=((items??[]) as any[]).map(i=>({...i,category:i.category??"sonstiges",status:i.status??"open",priority:i.priority??"normal",location_name:Array.isArray(i.company_locations)?i.company_locations[0]?.name??null:i.company_locations?.name??null,responsible_name:Array.isArray(i.profiles)?name(i.profiles[0]??{}):name(i.profiles??{}),measure_count:ms.filter(m=>m.qm_item_id===i.id).length,evidence_count:ev.filter(e=>e.qm_item_id===i.id).length})) as QmItem[];
const normMeasures=ms.map(m=>({...m,status:m.status??"open",priority:m.priority??"normal",item_title:Array.isArray(m.qm_items)?m.qm_items[0]?.title??null:m.qm_items?.title??null,responsible_name:Array.isArray(m.profiles)?name(m.profiles[0]??{}):name(m.profiles??{})})) as QmMeasure[];
const normEvidence=ev.map(e=>({...e,evidence_type:e.evidence_type??"note",item_title:Array.isArray(e.qm_items)?e.qm_items[0]?.title??null:e.qm_items?.title??null,document_title:Array.isArray(e.documents)?e.documents[0]?.file_name??null:e.documents?.file_name??null,created_by_name:Array.isArray(e.profiles)?name(e.profiles[0]??{}):name(e.profiles??{})})) as QmEvidence[];
const today=new Date();today.setHours(0,0,0,0);const overdueItems=normItems.filter(i=>i.status!=="completed"&&i.status!=="archived"&&i.due_date&&new Date(i.due_date)<today).length;const overdueMeasures=normMeasures.filter(m=>m.status!=="completed"&&m.due_date&&new Date(m.due_date)<today).length;
return{items:normItems,measures:normMeasures,evidence:normEvidence,locations:(locations??[]) as QmOption[],employees:((employees??[]) as any[]).map(e=>({id:e.id,name:name(e)})),documents:((documents??[]) as any[]).map(d=>({id:d.id,name:d.file_name??"Dokument"})),stats:{total:normItems.filter(i=>i.status!=="archived").length,open:normItems.filter(i=>i.status==="open").length,inProgress:normItems.filter(i=>i.status==="in_progress").length,overdue:overdueItems+overdueMeasures,completed:normItems.filter(i=>i.status==="completed").length,openMeasures:normMeasures.filter(m=>m.status==="open"||m.status==="in_progress").length,evidence:normEvidence.length,archived:normItems.filter(i=>i.status==="archived").length},exportPrepared:false}}
