"use server";
import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/lib/supabase-server";
const cats=["organisation","pflegeprozess","dokumentation","mitarbeiter","hygiene","medikamente","notfallmanagement","datenschutz","abrechnung","fortbildungen","beschwerden","md_vorbereitung","sonstiges"] as const;
const itemStatuses=["open","in_progress","waiting","completed","overdue","archived"] as const; const measureStatuses=["open","in_progress","completed","cancelled"] as const; const priorities=["low","normal","high","urgent"] as const; const evidenceTypes=["document","note","check","photo","other"] as const;
function cid(){return process.env.NURIA_DEV_COMPANY_ID??null} function uid(){return process.env.NURIA_DEV_USER_ID??null} function t(v:FormDataEntryValue|null){const s=typeof v==="string"?v.trim():"";return s||null} function req(fd:FormData,k:string){const v=t(fd.get(k));if(!v)throw new Error("Pflichtfeld fehlt.");return v} function one<T extends readonly string[]>(v:string|null,a:T,l:string){if(!v||!a.includes(v))throw new Error(`${l} ist ungültig.`);return v as T[number]} function d(v:string|null){if(!v)return null;const x=new Date(v);if(Number.isNaN(x.getTime()))throw new Error("Datum ist ungültig.");return v}
async function ref(table:"company_locations"|"profiles"|"qm_items"|"documents",id:string|null,companyId:string){if(!id)return null;const s=getSupabaseServerClient();if(!s)return null;const {data}=await s.from(table).select("id").eq("company_id",companyId).eq("id",id).maybeSingle();if(!data)throw new Error("Auswahl ist ungültig.");return id}
async function itemPayload(fd:FormData,companyId:string){const status=one(t(fd.get("status")),itemStatuses,"Status");return{title:req(fd,"title"),description:t(fd.get("description")),category:one(t(fd.get("category")),cats,"Kategorie"),status,priority:one(t(fd.get("priority")),priorities,"Priorität"),location_id:await ref("company_locations",t(fd.get("location_id")),companyId),responsible_user_id:await ref("profiles",t(fd.get("responsible_user_id")),companyId),due_date:d(t(fd.get("due_date"))),last_checked_at:d(t(fd.get("last_checked_at"))),notes:t(fd.get("notes")),completed_at:status==="completed"?new Date().toISOString():null,archived_at:status==="archived"?new Date().toISOString():null}}
async function measurePayload(fd:FormData,companyId:string){const status=one(t(fd.get("status")),measureStatuses,"Status");return{qm_item_id:await ref("qm_items",req(fd,"qm_item_id"),companyId),title:req(fd,"title"),description:t(fd.get("description")),status,priority:one(t(fd.get("priority")),priorities,"Priorität"),responsible_user_id:await ref("profiles",t(fd.get("responsible_user_id")),companyId),due_date:d(t(fd.get("due_date"))),notes:t(fd.get("notes")),completed_at:status==="completed"?new Date().toISOString():null}}
async function evidencePayload(fd:FormData,companyId:string){return{qm_item_id:await ref("qm_items",req(fd,"qm_item_id"),companyId),document_id:await ref("documents",t(fd.get("document_id")),companyId),title:req(fd,"title"),description:t(fd.get("description")),evidence_type:one(t(fd.get("evidence_type")),evidenceTypes,"Nachweistyp")}}
export async function createQmItem(fd:FormData){const s=getSupabaseServerClient(),c=cid();if(!s||!c)return;await s.from("qm_items").insert({...await itemPayload(fd,c),company_id:c,created_by:uid(),updated_by:uid()});revalidatePath("/dashboard/qm-md")}
export async function updateQmItem(fd:FormData){const s=getSupabaseServerClient(),c=cid(),id=req(fd,"id");if(!s||!c)return;await s.from("qm_items").update({...await itemPayload(fd,c),updated_by:uid()}).eq("id",id).eq("company_id",c);revalidatePath("/dashboard/qm-md")}
export async function changeQmItemStatus(fd:FormData){const s=getSupabaseServerClient(),c=cid(),id=req(fd,"id"),status=one(t(fd.get("status")),itemStatuses,"Status");if(!s||!c)return;await s.from("qm_items").update({status,completed_at:status==="completed"?new Date().toISOString():null,archived_at:status==="archived"?new Date().toISOString():null,updated_by:uid()}).eq("id",id).eq("company_id",c);revalidatePath("/dashboard/qm-md")}
export async function changeQmItemPriority(fd:FormData){const s=getSupabaseServerClient(),c=cid(),id=req(fd,"id"),priority=one(t(fd.get("priority")),priorities,"Priorität");if(!s||!c)return;await s.from("qm_items").update({priority,updated_by:uid()}).eq("id",id).eq("company_id",c);revalidatePath("/dashboard/qm-md")}
export async function setQmItemDueDate(fd:FormData){const s=getSupabaseServerClient(),c=cid(),id=req(fd,"id");if(!s||!c)return;await s.from("qm_items").update({due_date:d(t(fd.get("due_date"))),updated_by:uid()}).eq("id",id).eq("company_id",c);revalidatePath("/dashboard/qm-md")}
export async function createQmMeasure(fd:FormData){const s=getSupabaseServerClient(),c=cid();if(!s||!c)return;await s.from("qm_measures").insert({...await measurePayload(fd,c),company_id:c,created_by:uid(),updated_by:uid()});revalidatePath("/dashboard/qm-md")}
export async function updateQmMeasure(fd:FormData){const s=getSupabaseServerClient(),c=cid(),id=req(fd,"id");if(!s||!c)return;await s.from("qm_measures").update({...await measurePayload(fd,c),updated_by:uid()}).eq("id",id).eq("company_id",c);revalidatePath("/dashboard/qm-md")}
export async function changeQmMeasureStatus(fd:FormData){const s=getSupabaseServerClient(),c=cid(),id=req(fd,"id"),status=one(t(fd.get("status")),measureStatuses,"Status");if(!s||!c)return;await s.from("qm_measures").update({status,completed_at:status==="completed"?new Date().toISOString():null,updated_by:uid()}).eq("id",id).eq("company_id",c);revalidatePath("/dashboard/qm-md")}
export async function changeQmMeasurePriority(fd:FormData){const s=getSupabaseServerClient(),c=cid(),id=req(fd,"id"),priority=one(t(fd.get("priority")),priorities,"Priorität");if(!s||!c)return;await s.from("qm_measures").update({priority,updated_by:uid()}).eq("id",id).eq("company_id",c);revalidatePath("/dashboard/qm-md")}
export async function createQmEvidence(fd:FormData){const s=getSupabaseServerClient(),c=cid();if(!s||!c)return;await s.from("qm_evidence").insert({...await evidencePayload(fd,c),company_id:c,created_by:uid()});revalidatePath("/dashboard/qm-md")}
