"use server";

import { revalidatePath } from "next/cache";
import { getSupabaseServerClient } from "@/lib/supabase-server";
import type { TimeEntrySource, TimeEntryStatus, TimeEntryType } from "@/lib/time-tracking";

const statuses = ["draft", "submitted", "approved", "rejected", "corrected"] as const;
const types = ["work_time", "client_visit", "tour_time", "break", "admin_time", "other"] as const;
const sources = ["manual", "tour_wizard", "system"] as const;
function cid() { return process.env.NURIA_DEV_COMPANY_ID ?? null; }
function uid() { return process.env.NURIA_DEV_USER_ID ?? null; }
function txt(v: FormDataEntryValue | null) { const s = typeof v === "string" ? v.trim() : ""; return s || null; }
function req(fd: FormData, k: string) { const v = txt(fd.get(k)); if (!v) throw new Error("Pflichtfeld fehlt."); return v; }
function status(v: string | null): TimeEntryStatus { if (!v || !statuses.includes(v as TimeEntryStatus)) throw new Error("Status ist ungültig."); return v as TimeEntryStatus; }
function typ(v: string | null): TimeEntryType { if (!v || !types.includes(v as TimeEntryType)) throw new Error("Eintragstyp ist ungültig."); return v as TimeEntryType; }
function source(v: string | null): TimeEntrySource { if (!v || !sources.includes(v as TimeEntrySource)) throw new Error("Quelle ist ungültig."); return v as TimeEntrySource; }
function minutes(start: string, end: string, br: number) { if (start > end) throw new Error("Startzeit darf nicht nach Endzeit liegen."); if (br < 0) throw new Error("Pause darf nicht negativ sein."); const [sh, sm] = start.split(":").map(Number); const [eh, em] = end.split(":").map(Number); return Math.max(0, eh * 60 + em - (sh * 60 + sm) - br); }
async function own(table: string, companyId: string, id: string | null) { if (!id) return null; const supabase = getSupabaseServerClient(); if (!supabase) return null; const { data } = await supabase.from(table).select("id").eq("company_id", companyId).eq("id", id).maybeSingle(); if (!data) throw new Error("Zuweisung ist ungültig."); return id; }
async function payload(fd: FormData, companyId: string) { const start = req(fd, "start_time"); const end = req(fd, "end_time"); const br = Number(txt(fd.get("break_minutes")) ?? "0"); return { employee_id: await own("profiles", companyId, req(fd, "employee_id")), entry_date: req(fd, "entry_date"), start_time: start, end_time: end, break_minutes: br, duration_minutes: minutes(start, end, br), entry_type: typ(txt(fd.get("entry_type"))), status: status(txt(fd.get("status"))), source: source(txt(fd.get("source")) ?? "manual"), location_id: await own("company_locations", companyId, txt(fd.get("location_id"))), client_id: await own("clients", companyId, txt(fd.get("client_id"))), shift_id: await own("shifts", companyId, txt(fd.get("shift_id"))), tour_id: await own("tours", companyId, txt(fd.get("tour_id"))), tour_stop_id: await own("tour_stops", companyId, txt(fd.get("tour_stop_id"))), notes: txt(fd.get("notes")) }; }
async function audit(companyId: string, id: string, action: string, newValues: unknown) { const supabase = getSupabaseServerClient(); if (supabase) await supabase.from("time_entry_audit_logs").insert({ company_id: companyId, time_entry_id: id, changed_by: uid(), action, new_values: newValues }); }
export async function createTimeEntry(fd: FormData) { const supabase = getSupabaseServerClient(); const companyId = cid(); if (!supabase || !companyId) return; const row = { ...(await payload(fd, companyId)), company_id: companyId, created_by: uid(), updated_by: uid() }; const { data } = await supabase.from("time_entries").insert(row).select("id").single(); if (data) await audit(companyId, data.id, "created", row); revalidatePath("/dashboard/zeiterfassung"); }
export async function updateTimeEntry(fd: FormData) { const supabase = getSupabaseServerClient(); const companyId = cid(); const id = req(fd, "id"); if (!supabase || !companyId) return; const row = { ...(await payload(fd, companyId)), updated_by: uid() }; await supabase.from("time_entries").update(row).eq("id", id).eq("company_id", companyId); await audit(companyId, id, row.status === "corrected" ? "corrected" : "updated", row); revalidatePath("/dashboard/zeiterfassung"); }
export async function reviewTimeEntry(fd: FormData) { const supabase = getSupabaseServerClient(); const companyId = cid(); const id = req(fd, "id"); const next = status(req(fd, "status")); if (!supabase || !companyId) return; const row = { status: next, reviewed_by: uid(), reviewed_at: new Date().toISOString(), updated_by: uid() }; await supabase.from("time_entries").update(row).eq("id", id).eq("company_id", companyId); await audit(companyId, id, next === "approved" ? "approved" : next === "rejected" ? "rejected" : "corrected", row); revalidatePath("/dashboard/zeiterfassung"); }
