"use client";
import { AnimatePresence, motion } from "framer-motion";
import { Pencil, Plus, X } from "lucide-react";
import { useState } from "react";
import type { QmMdData, QmItem, QmMeasure, QmEvidence } from "@/lib/qm-md";
type Common={data:QmMdData;action:(fd:FormData)=>void;buttonLabel:string;submitLabel:string};
type ItemProps=Common&{item?:QmItem};
type MeasureProps=Common&{measure?:QmMeasure;itemId?:string};
type EvidenceProps=Common&{evidence?:QmEvidence;itemId?:string};
const cats=[["organisation","Organisation"],["pflegeprozess","Pflegeprozess"],["dokumentation","Dokumentation"],["mitarbeiter","Mitarbeiter"],["hygiene","Hygiene"],["medikamente","Medikamente"],["notfallmanagement","Notfallmanagement"],["datenschutz","Datenschutz"],["abrechnung","Abrechnung"],["fortbildungen","Fortbildungen"],["beschwerden","Beschwerden"],["md_vorbereitung","MD-Vorbereitung"],["sonstiges","Sonstiges"]] as const;
const itemStatuses=[["open","Offen"],["in_progress","In Bearbeitung"],["waiting","Wartet"],["completed","Erledigt"],["overdue","Überfällig"],["archived","Archiviert"]] as const;
const measureStatuses=[["open","Offen"],["in_progress","In Bearbeitung"],["completed","Erledigt"],["cancelled","Abgebrochen"]] as const;
const priorities=[["low","Niedrig"],["normal","Normal"],["high","Hoch"],["urgent","Dringend"]] as const; const evidenceTypes=[["document","Dokument"],["note","Notiz"],["check","Prüfung"],["photo","Foto"],["other","Sonstiges"]] as const;
function Shell({open,setOpen,title,children}:{open:boolean;setOpen:(v:boolean)=>void;title:string;children:React.ReactNode}){return <AnimatePresence>{open?<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="modal-panel qm-modal-panel" initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10,scale:.98}}><div className="modal-header"><div><h2>{title}</h2><p>Die Seite unterstützt die interne Organisation von Qualitätsmanagement, Nachweisen und MD-Vorbereitungen.</p></div><button className="modal-close" type="button" onClick={()=>setOpen(false)} aria-label="Schließen"><X size={18}/></button></div>{children}</motion.div></motion.div>:null}</AnimatePresence>}
export function QmItemModal({data,action,buttonLabel,submitLabel,item}:ItemProps){const[open,setOpen]=useState(false);return <><motion.button className="button" onClick={()=>setOpen(true)} type="button" whileHover={{y:-1}} whileTap={{scale:.98}}>{item?<Pencil size={16}/>:<Plus size={16}/>} {buttonLabel}</motion.button><Shell open={open} setOpen={setOpen} title={buttonLabel}><form action={action} className="qm-form">{item?<input name="id" type="hidden" value={item.id}/>:null}<fieldset><legend>Prüfpunkt</legend><label className="qm-form-wide">Titel<input name="title" required defaultValue={item?.title??""}/></label><label className="qm-form-wide">Beschreibung<textarea name="description" rows={4} defaultValue={item?.description??""}/></label><label>Kategorie<select name="category" required defaultValue={item?.category??"sonstiges"}>{cats.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select name="status" required defaultValue={item?.status??"open"}>{itemStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Priorität<select name="priority" required defaultValue={item?.priority??"normal"}>{priorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Standort<select name="location_id" defaultValue={item?.location_id??""}><option value="">Kein Standort</option>{data.locations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Verantwortliche Person<select name="responsible_user_id" defaultValue={item?.responsible_user_id??""}><option value="">Nicht zugewiesen</option>{data.employees.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Fälligkeitsdatum<input name="due_date" type="date" defaultValue={item?.due_date??""}/></label><label>Letzte Prüfung<input name="last_checked_at" type="date" defaultValue={item?.last_checked_at??""}/></label><label className="qm-form-wide">Notizen<textarea name="notes" rows={4} defaultValue={item?.notes??""}/></label></fieldset><div className="qm-form-actions"><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Abbrechen</button><button className="button">{submitLabel}</button></div></form></Shell></>}
export function QmMeasureModal({data,action,buttonLabel,submitLabel,measure,itemId}:MeasureProps){const[open,setOpen]=useState(false);return <><motion.button className="button" onClick={()=>setOpen(true)} type="button" whileHover={{y:-1}} whileTap={{scale:.98}}>{measure?<Pencil size={16}/>:<Plus size={16}/>} {buttonLabel}</motion.button><Shell open={open} setOpen={setOpen} title={buttonLabel}><form action={action} className="qm-form">{measure?<input name="id" type="hidden" value={measure.id}/>:null}<fieldset><legend>Maßnahme</legend><label className="qm-form-wide">Zugehöriger Prüfpunkt<select name="qm_item_id" required defaultValue={measure?.qm_item_id??itemId??""}>{data.items.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label>{data.items.length===0?<p className="qm-form-wide">Noch keine Prüfpunkte vorhanden. Bitte zuerst Prüfpunkt anlegen.</p>:null}<label className="qm-form-wide">Titel<input name="title" required defaultValue={measure?.title??""}/></label><label className="qm-form-wide">Beschreibung<textarea name="description" rows={4} defaultValue={measure?.description??""}/></label><label>Status<select name="status" required defaultValue={measure?.status??"open"}>{measureStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Priorität<select name="priority" required defaultValue={measure?.priority??"normal"}>{priorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Verantwortliche Person<select name="responsible_user_id" defaultValue={measure?.responsible_user_id??""}><option value="">Nicht zugewiesen</option>{data.employees.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Fälligkeitsdatum<input name="due_date" type="date" defaultValue={measure?.due_date??""}/></label><label className="qm-form-wide">Notizen<textarea name="notes" rows={4} defaultValue={measure?.notes??""}/></label></fieldset><div className="qm-form-actions"><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Abbrechen</button><button className="button">{submitLabel}</button></div></form></Shell></>}
export function QmEvidenceModal({data,action,buttonLabel,submitLabel,evidence,itemId}:EvidenceProps){const[open,setOpen]=useState(false);return <><motion.button className="button" onClick={()=>setOpen(true)} type="button" whileHover={{y:-1}} whileTap={{scale:.98}}>{evidence?<Pencil size={16}/>:<Plus size={16}/>} {buttonLabel}</motion.button><Shell open={open} setOpen={setOpen} title={buttonLabel}><form action={action} className="qm-form">{evidence?<input name="id" type="hidden" value={evidence.id}/>:null}<fieldset><legend>Nachweis</legend><label>Zugehöriger Prüfpunkt<select name="qm_item_id" required defaultValue={evidence?.qm_item_id??itemId??""}>{data.items.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label><label>Nachweis-Typ<select name="evidence_type" required defaultValue={evidence?.evidence_type??"note"}>{evidenceTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="qm-form-wide">Titel<input name="title" required defaultValue={evidence?.title??""}/></label><label className="qm-form-wide">Beschreibung<textarea name="description" rows={4} defaultValue={evidence?.description??""}/></label><label className="qm-form-wide">Dokument<select name="document_id" defaultValue={evidence?.document_id??""}><option value="">Kein Dokument</option>{data.documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{data.documents.length===0?<p className="qm-form-wide">Noch keine Dokumente vorhanden. Nachweis kann ohne Dokument angelegt werden.</p>:null}</fieldset><div className="qm-form-actions"><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Abbrechen</button><button className="button">{submitLabel}</button></div></form></Shell></>}
