"use client";

import { AnimatePresence, motion } from "framer-motion";
import { CheckCircle2, Clock, Download, Eye, FilterX, Search, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { TimeEntryModal } from "@/components/time-entry-modal";
import type { TimeEntryStatus, TimeEntryType, TimeEntrySource, TimeTrackingData } from "@/lib/time-tracking";

type Props = { data: TimeTrackingData; actions: { createTimeEntry: (formData: FormData) => void; updateTimeEntry: (formData: FormData) => void; reviewTimeEntry: (formData: FormData) => void } };
const statusLabels: Record<TimeEntryStatus, string> = { draft: "Entwurf", submitted: "Eingereicht", approved: "Freigegeben", rejected: "Abgelehnt", corrected: "Korrigiert" };
const typeLabels: Record<TimeEntryType, string> = { work_time: "Arbeitszeit", client_visit: "Klientenbesuch", tour_time: "Tourzeit", break: "Pause", admin_time: "Verwaltungszeit", other: "Sonstiges" };
const sourceLabels: Record<TimeEntrySource, string> = { manual: "Manuell", tour_wizard: "Tour-Wizard", system: "System" };
function fmt(min: number) { return `${Math.floor(min / 60)}:${String(min % 60).padStart(2, "0")} Std.`; }
function val(v: string | null | undefined) { return v && v.trim() ? v : "Nicht hinterlegt"; }
function key(d: Date) { return d.toISOString().slice(0, 10); }
function range(view: "day" | "week" | "month", dateKey: string) { const d = new Date(`${dateKey}T00:00:00`); if (view === "day") return { s: dateKey, e: dateKey }; if (view === "week") { const day = d.getDay() || 7; const s = new Date(d); s.setDate(d.getDate() - day + 1); const e = new Date(s); e.setDate(s.getDate() + 6); return { s: key(s), e: key(e) }; } return { s: key(new Date(d.getFullYear(), d.getMonth(), 1)), e: key(new Date(d.getFullYear(), d.getMonth() + 1, 0)) }; }

export function TimeTrackingPage({ data, actions }: Props) {
  const [view, setView] = useState<"day" | "week" | "month">("day"); const [date, setDate] = useState(data.today); const [query, setQuery] = useState(""); const [employee, setEmployee] = useState("all"); const [location, setLocation] = useState("all"); const [client, setClient] = useState("all"); const [status, setStatus] = useState("all"); const [type, setType] = useState("all"); const [source, setSource] = useState("all"); const r = range(view, date);
  const filtered = useMemo(() => data.entries.filter((e) => { const hay = [e.employee_name, e.client_name, e.location_name, e.notes].filter(Boolean).join(" ").toLowerCase(); const q = query.trim().toLowerCase(); return e.entry_date >= r.s && e.entry_date <= r.e && (!q || hay.includes(q)) && (employee === "all" || e.employee_id === employee) && (location === "all" || (location === "none" ? !e.location_id : e.location_id === location)) && (client === "all" || (client === "none" ? !e.client_id : e.client_id === client)) && (status === "all" || e.status === status) && (type === "all" || e.entry_type === type) && (source === "all" || e.source === source); }), [client, data.entries, employee, location, query, r.e, r.s, source, status, type]);
  const stats = [["Stunden heute", fmt(data.stats.todayMinutes), Clock], ["Stunden diese Woche", fmt(data.stats.weekMinutes), Clock], ["Stunden dieser Monat", fmt(data.stats.monthMinutes), Clock], ["Offene Einträge", data.stats.open, Clock], ["Freigegeben", data.stats.approved, CheckCircle2], ["Abgelehnt", data.stats.rejected, XCircle], ["Korrigiert", data.stats.corrected, Clock], ["Ohne Mitarbeiter", data.stats.withoutEmployee, Clock]] as const;
  function move(n: number) { const d = new Date(`${date}T00:00:00`); if (view === "day") d.setDate(d.getDate() + n); if (view === "week") d.setDate(d.getDate() + n * 7); if (view === "month") d.setMonth(d.getMonth() + n); setDate(key(d)); }
  return <motion.section className="page time-page" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><div className="time-header"><div><h1>Zeiterfassung</h1><p>Prüfen und verwalten Sie Arbeitszeiten, Einsatzzeiten und Nachweise Ihres Pflegedienstes.</p></div><div className="time-header-actions"><TimeEntryModal action={actions.createTimeEntry} buttonLabel="Zeiteintrag anlegen" submitLabel="Zeiteintrag anlegen" data={data} /><button className="button secondary" disabled title="Export wird vorbereitet." type="button"><Download size={16} />Zeiten exportieren</button></div></div>
    <div className="time-stats-grid">{stats.map(([label, value, Icon], i) => <motion.div className="stat-card" key={label} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.02 }}><div className="stat-icon"><Icon size={18} /></div><span>{label}</span><strong>{value}</strong></motion.div>)}</div>
    <motion.div className="time-viewbar"><div className="segmented">{(["day", "week", "month"] as const).map((x) => <button key={x} className={view === x ? "active" : ""} type="button" onClick={() => setView(x)}>{x === "day" ? "Tag" : x === "week" ? "Woche" : "Monat"}</button>)}</div><button className="button secondary" type="button" onClick={() => move(-1)}>Zurück</button><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /><button className="button secondary" type="button" onClick={() => setDate(data.today)}>Heute</button><button className="button secondary" type="button" onClick={() => move(1)}>Weiter</button></motion.div>
    <motion.div className="time-filter-panel"><label><Search size={16} />Suche<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Mitarbeiter, Klient, Standort, Notiz" /></label><label>Mitarbeiter<select value={employee} onChange={(e) => setEmployee(e.target.value)}><option value="all">Alle</option>{data.employees.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Standort<select value={location} onChange={(e) => setLocation(e.target.value)}><option value="all">Alle</option><option value="none">Ohne Standort</option>{data.locations.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Klient<select value={client} onChange={(e) => setClient(e.target.value)}><option value="all">Alle</option><option value="none">Ohne Klient</option>{data.clients.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Alle</option>{Object.entries(statusLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>Typ<select value={type} onChange={(e) => setType(e.target.value)}><option value="all">Alle</option>{Object.entries(typeLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>Quelle<select value={source} onChange={(e) => setSource(e.target.value)}><option value="all">Alle</option>{Object.entries(sourceLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><button className="button secondary" type="button" onClick={() => { setQuery(""); setEmployee("all"); setLocation("all"); setClient("all"); setStatus("all"); setType("all"); setSource("all"); }}><FilterX size={16} />Zurücksetzen</button></motion.div>
    <motion.section className="time-proof-panel"><h2>Arbeitszeitnachweis</h2><div className="time-proof-grid">{data.proofRows.map((row) => <div key={row.employeeId}><strong>{row.employeeName}</strong><span>Gesamt: {fmt(row.total)}</span><span>Arbeitszeit: {fmt(row.work)}</span><span>Klientenbesuche: {fmt(row.visits)}</span><span>Pausen: {fmt(row.breaks)}</span><span>Verwaltung: {fmt(row.admin)}</span><span>Offen/Freigegeben: {row.open}/{row.approved}</span></div>)}</div></motion.section>
    <AnimatePresence>{data.entries.length === 0 ? null : <motion.div className="time-list">{filtered.map((e) => <motion.article className="time-card" key={e.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><div className="time-card-header"><div><span>{new Intl.DateTimeFormat("de-DE").format(new Date(e.entry_date))} · {e.start_time} - {e.end_time}</span><h2>{val(e.employee_name)}</h2></div><div className="client-badges"><span className={`time-type-badge type-${e.entry_type}`}>{typeLabels[e.entry_type]}</span><span className={`time-status ${e.status}`}>{statusLabels[e.status]}</span><span className="shift-type-badge">{sourceLabels[e.source]}</span></div></div><div className="time-details-grid"><div><span>Pause</span><strong>{e.break_minutes} Min.</strong></div><div><span>Dauer</span><strong>{fmt(e.duration_minutes)}</strong></div><div><span>Klient</span><strong>{val(e.client_name)}</strong></div><div><span>Tour</span><strong>{val(e.tour_name)}</strong></div><div><span>Standort</span><strong>{val(e.location_name)}</strong></div><div><span>Notiz</span><strong>{val(e.notes)}</strong></div></div><div className="location-actions"><details><summary><Eye size={15} />Ansehen</summary><div className="location-detail-panel"><p>Datum: {new Intl.DateTimeFormat("de-DE").format(new Date(e.entry_date))}</p><p>Mitarbeiter: {val(e.employee_name)}</p><p>Start/Ende: {e.start_time} - {e.end_time}</p><p>Pause: {e.break_minutes} Minuten</p><p>Dauer: {fmt(e.duration_minutes)}</p><p>Typ: {typeLabels[e.entry_type]}</p><p>Status: {statusLabels[e.status]}</p><p>Quelle: {sourceLabels[e.source]}</p><p>Standort: {val(e.location_name)}</p><p>Klient: {val(e.client_name)}</p><p>Dienst: {val(e.shift_name)}</p><p>Tour: {val(e.tour_name)}</p><p>Tourstopp: {val(e.tour_stop_name)}</p><p>Notizen: {val(e.notes)}</p><p>Geprüft von: {val(e.reviewed_by_name)}</p><p>Geprüft am: {val(e.reviewed_at)}</p><p>Erstellt von: {val(e.created_by_name)}</p><p>Zuletzt aktualisiert: {new Intl.DateTimeFormat("de-DE").format(new Date(e.updated_at))}</p></div></details><TimeEntryModal action={actions.updateTimeEntry} buttonLabel="Bearbeiten" submitLabel="Änderungen speichern" data={data} entry={e} />{(["approved", "rejected", "corrected"] as TimeEntryStatus[]).map((s) => <form action={actions.reviewTimeEntry} key={s}><input name="id" type="hidden" value={e.id} /><input name="status" type="hidden" value={s} /><button className="button secondary" type="submit">{statusLabels[s]}</button></form>)}</div></motion.article>)}</motion.div>}</AnimatePresence></motion.section>;
}
