"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Pencil, Plus, X } from "lucide-react";
import { useState } from "react";
import type { OnlineOption, OnlinePresenceTask, WebsiteLead } from "@/lib/website-online";

type Common = { locations: OnlineOption[]; employees: OnlineOption[] };
type LeadProps = Common & { action: (fd: FormData) => void; lead?: WebsiteLead; buttonLabel: string; submitLabel: string };
type TaskProps = Common & { action: (fd: FormData) => void; task?: OnlinePresenceTask; buttonLabel: string; submitLabel: string };

const leadTypes = [["general","Allgemein"],["care_request","Pflegeanfrage"],["callback_request","Rückrufwunsch"],["job_application","Bewerbung"],["cooperation","Kooperation"],["complaint","Beschwerde"],["other","Sonstiges"]] as const;
const sources = [["website","Website"],["contact_form","Kontaktformular"],["phone","Telefon"],["email","E-Mail"],["facebook","Facebook"],["instagram","Instagram"],["google","Google"],["recommendation","Empfehlung"],["manual","Manuell"],["other","Sonstiges"]] as const;
const leadStatuses = [["new","Neu"],["in_progress","In Bearbeitung"],["waiting","Wartet"],["done","Erledigt"],["rejected","Abgelehnt"],["archived","Archiviert"]] as const;
const priorities = [["low","Niedrig"],["normal","Normal"],["high","Hoch"],["urgent","Dringend"]] as const;
const taskTypes = [["website_update","Website-Aktualisierung"],["google_profile","Google-Profil"],["social_media","Social Media"],["content","Inhalte"],["photos","Fotos"],["job_posting","Stellenanzeige"],["review_management","Bewertungen"],["other","Sonstiges"]] as const;
const taskStatuses = [["open","Offen"],["in_progress","In Bearbeitung"],["done","Erledigt"],["archived","Archiviert"]] as const;

function dt(value?: string | null) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 16); }

function Shell({ open, setOpen, title, children }: { open: boolean; setOpen: (v: boolean) => void; title: string; children: React.ReactNode }) {
  return <AnimatePresence>{open ? <motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="modal-panel website-modal-panel" initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10,scale:.98}}><div className="modal-header"><div><h2>{title}</h2><p>Die Seite unterstützt die interne Verwaltung von Online-Anfragen und Aufgaben zur digitalen Außenwirkung.</p></div><button className="modal-close" type="button" onClick={()=>setOpen(false)} aria-label="Schließen"><X size={18}/></button></div>{children}</motion.div></motion.div> : null}</AnimatePresence>;
}

export function WebsiteLeadModal({ action, lead, buttonLabel, submitLabel, locations, employees }: LeadProps) {
  const [open,setOpen]=useState(false);
  return <><motion.button className="button" type="button" onClick={()=>setOpen(true)} whileHover={{y:-1}} whileTap={{scale:.98}}>{lead?<Pencil size={16}/>:<Plus size={16}/>} {buttonLabel}</motion.button><Shell open={open} setOpen={setOpen} title={buttonLabel}><form action={action} className="website-form">{lead?<input name="id" type="hidden" value={lead.id}/>:null}<fieldset><legend>Kontakt</legend><label>Vorname<input name="first_name" defaultValue={lead?.first_name??""}/></label><label>Nachname<input name="last_name" defaultValue={lead?.last_name??""}/></label><label>Organisation<input name="organization_name" defaultValue={lead?.organization_name??""}/></label><label>E-Mail<input name="email" type="email" defaultValue={lead?.email??""}/></label><label>Telefon<input name="phone" defaultValue={lead?.phone??""}/></label></fieldset><fieldset><legend>Anfrage</legend><label className="website-form-wide">Betreff<input name="subject" required defaultValue={lead?.subject??""}/></label><label className="website-form-wide">Nachricht<textarea name="message" rows={4} defaultValue={lead?.message??""}/></label><label>Lead-Typ<select name="lead_type" required defaultValue={lead?.lead_type??"general"}>{leadTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Quelle<select name="source" required defaultValue={lead?.source??"website"}>{sources.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select name="status" required defaultValue={lead?.status??"new"}>{leadStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Priorität<select name="priority" required defaultValue={lead?.priority??"normal"}>{priorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></fieldset><fieldset><legend>Organisation intern</legend><label>Standort<select name="location_id" defaultValue={lead?.location_id??""}><option value="">Kein Standort</option>{locations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Zugewiesen an<select name="assigned_to" defaultValue={lead?.assigned_to??""}><option value="">Nicht zugewiesen</option>{employees.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Letzte Kontaktaufnahme<input name="last_contact_at" type="datetime-local" defaultValue={dt(lead?.last_contact_at)}/></label><label>Nächste Wiedervorlage<input name="next_follow_up_at" type="datetime-local" defaultValue={dt(lead?.next_follow_up_at)}/></label><label className="website-form-wide">Notizen<textarea name="notes" rows={4} defaultValue={lead?.notes??""}/></label></fieldset><div className="website-form-actions"><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Abbrechen</button><button className="button" type="submit">{submitLabel}</button></div></form></Shell></>;
}

export function OnlineTaskModal({ action, task, buttonLabel, submitLabel, locations, employees }: TaskProps) {
  const [open,setOpen]=useState(false);
  return <><motion.button className="button" type="button" onClick={()=>setOpen(true)} whileHover={{y:-1}} whileTap={{scale:.98}}>{task?<Pencil size={16}/>:<Plus size={16}/>} {buttonLabel}</motion.button><Shell open={open} setOpen={setOpen} title={buttonLabel}><form action={action} className="website-form">{task?<input name="id" type="hidden" value={task.id}/>:null}<fieldset><legend>Aufgabe</legend><label className="website-form-wide">Titel<input name="title" required defaultValue={task?.title??""}/></label><label className="website-form-wide">Beschreibung<textarea name="description" rows={4} defaultValue={task?.description??""}/></label><label>Aufgabentyp<select name="task_type" required defaultValue={task?.task_type??"other"}>{taskTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select name="status" required defaultValue={task?.status??"open"}>{taskStatuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Priorität<select name="priority" required defaultValue={task?.priority??"normal"}>{priorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Fälligkeitsdatum<input name="due_date" type="date" defaultValue={task?.due_date??""}/></label><label>Standort<select name="location_id" defaultValue={task?.location_id??""}><option value="">Kein Standort</option>{locations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Zugewiesen an<select name="assigned_to" defaultValue={task?.assigned_to??""}><option value="">Nicht zugewiesen</option>{employees.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label></fieldset><div className="website-form-actions"><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Abbrechen</button><button className="button" type="submit">{submitLabel}</button></div></form></Shell></>;
}

